### PR TITLE
RqB

### PR DESCRIPTION
**Pull request by ENnaraghi**
Services

### CODE REVIEW

**Comment by EhsanNaraghi** [comment]
[Dashboard](https://trello.com/c/nakq2dFT/1-dashboard)

**Comment by EhsanNaraghi** [comment]
:/

**Comment by ENnaraghi** [comment]
[Going live with server deployment](https://trello.com/c/0Cl7lPUl/5-going-live-with-server-deployment)

**Comment by ENnaraghi** [comment]
Agile boards

**Pull request merged**
